### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by andonicio** [tobozo/WUD-Ducky#10]
Hello,
Let's see if anyone can help me, I'm stuck in the compilation. I'm a beginner and I can't solve it. I get this error when compiling;

In file included from C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main/WebServer.h:30,
                 from C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main/WebServer.h:30,
                 from C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main/WebServer.h:30,
                 from C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main\WUD-Ducky\WUD-Ducky.ino:39:
C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main/WebServer.h:27:18: error: #include nested too deeply
 #include <WiFi.h>
                  ^
C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main/WebServer.h:28:24: error: #include nested too deeply
 #include <WiFiClient.h>
                        ^
C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main/WebServer.h:29:20: error: #include nested too deeply
 #include <WiFiAP.h>
                    ^
C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main/WebServer.h:30:23: error: #include nested too deeply
 #include <WebServer.h>
                       ^
C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main/WebServer.h:31:20: error: #include nested too deeply
 #include <SPIFFS.h>
In file included from C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main/WebServer.h:30,
                 from C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main/WebServer.h:30,
                 from C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main/WebServer.h:30,
                 from C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main/WebServer.h:30,
                   from C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main\WUD-Ducky\WUD-Ducky.ino:39:
C:\Users\BMG\Documents\Arduino\libraries\WUD-Ducky-main/WebServer.h:31:10: fatal error: SPIFFS.h: No such file or directory
 #include <SPIFFS.h>
          ^~~~~~~~~~
compilation terminated.

**Comment by tobozo** [comment]
sorry about taking so long to reply, this project should be deployed in the sketchbook folder, not the libraries folder
