### ISSUE TITLE
WUD v1.2 Not Recognized as Keyboard/Mouse

### ISSUE THREAD

**Issue by XD4N6** [tobozo/WUD-Ducky#25]
Each time I plug the WUD v1.2 into my computer, it is not recognized as a keyboard or mouse. I’m assuming this behavior might be normal, but I’m not sure.

(my esptinyusb ver is 1.3.4)
(and the core esp is 2.0.0)

Below are some screenshots of the issue:

![image](https://github.com/user-attachments/assets/ec126dcc-8b89-4bb7-8127-021999154aa0)

![image](https://github.com/user-attachments/assets/9fb24822-40cf-47f1-95be-3fe2ebd7db0a)
![image](https://github.com/user-attachments/assets/974b8d8d-cfd1-4fa0-86a7-828438e856e7)

Is there any way to fix this? Or could the issue be related to my WUD v1.2 device?

Thanks in advance for your help!

**Comment by tobozo** [comment]
hi,

wud-ducky hasn't been much tested on windows, it may conflict with hybrid HID devices on some laptops

however some of the warnings in that screenshot are related to the board settings, so what you can try is:

1) use [arduino core 2.0.2](https://github.com/espressif/arduino-esp32/releases/tag/2.0.2)
2) install [that board](https://github.com/tobozo/WUD-Ducky/tree/arduino-esp32-2.0.2/board) in the Arduino IDE
3) use [wud-ducky for arduino core 2.0.2](https://github.com/tobozo/WUD-Ducky/tree/arduino-esp32-2.0.2)
4) use [usbview](https://learn.microsoft.com/windows-hardware/drivers/debugger/usbview#where-to-get-usbview) to debug

**Comment by tobozo** [comment]
also you don't need `ESP32TinyUSB` since the arduino core 2.0.2 comes with its own version of tinyUSB

**Comment by XD4N6** [comment]
> hi,
> 
> wud-ducky hasn't been much tested on windows, it may conflict with hybrid HID devices on some laptops
> 
> however some of the warnings in that screenshot are related to the board settings, so what you can try is:
> 
> 1. use [arduino core 2.0.2](https://github.com/espressif/arduino-esp32/releases/tag/2.0.2)
> 2. install [that board](https://github.com/tobozo/WUD-Ducky/tree/arduino-esp32-2.0.2/board) in the Arduino IDE
> 3. use [wud-ducky for arduino core 2.0.2](https://github.com/tobozo/WUD-Ducky/tree/arduino-esp32-2.0.2)
> 4. use [usbview](https://learn.microsoft.com/windows-hardware/drivers/debugger/usbview#where-to-get-usbview) to debug

Thank you so much, and apologies for the delayed response. I flashed it with Arduino-ESP32-2.0.3-RC1 branch and spent some time resolving a few issues, but everything is working perfectly now!
