### ISSUE TITLE
SD Card Mount Failed

### ISSUE THREAD

**Issue by Ciph3rCat** [tobozo/WUD-Ducky#5]
I'm trying to upload files to SD card. When I switch to sd card, I get mount failed error. I am using 32GB SanDisk card in FAT32 format and it works fine in card reader. 

What could be wrong? 

Here's relevant **log from system log**:
```
[@00:00:01.952] SD Card Mount attempt: 0
[@00:00:02.652] SD Card Mount attempt: 1
[@00:00:03.352] SD Card Mount attempt: 2
[@00:00:04.052] SD Card Mount attempt: 3
[@00:00:04.752] SD Card Mount attempt: 4
[@00:00:05.452] SD Card Mount attempt: 5
[@00:00:06.152] SD Card Mount attempt: 6
[@00:00:06.852] SD Card Mount attempt: 7
[@00:00:07.552] SD Card Mount attempt: 8
[@00:00:08.252] SD Card Mount attempt: 9
[@00:00:08.952] SD Card Mount attempt: 10
[@00:00:09.652] SD Card Mount attempt: 11
[@00:00:09.752] SD Card Mount Failed
[@00:00:09.752] Error, PenDrive disabled
[@00:00:09.752] SD Card not present, spawning fake partition
[@00:00:09.752] USB already started
[@00:00:14.783] Pref defaulted: AP_SSID='WUD-01' (default='WUD-01')
[@00:00:14.784] Pref defaulted: 
```

**Comment by tobozo** [comment]
this is a known bug in the sdk with a know workaround, see [this thread](https://github.com/espressif/arduino-esp32/issues/6081)

closing this issue as redundand

**Comment by Ciph3rCat** [comment]
I followed thread and removed 4 lines from `ff_sd_status` function from `sd_diskio.cpp` file. Closed the arduino and even restarted system and re-flash on device but same result. Did I miss any step?

**Comment by tobozo** [comment]
Full power cycle is required when messing with the SPI bus, so make sure you fully unplug the ESP from any power source (this includes battery) after modifying the SD library or anything else inside the espressif sdk folder.

The annoying situation is that this SD component manages failure differently on reset, cold and hot boot, using a full power cycle is the only way to have a valid test result.
In some situations I even had to repeat the power cycle without SD card before it got detected.

From the roadmap to 2.0.3 I understand there are [several other issues](https://github.com/orgs/espressif/projects/3) involving Wire so there's still hope :-)
