### ISSUE TITLE
HID Timed out when using mouse or keyboard when payload running

### ISSUE THREAD

**Issue by maytinh365** [tobozo/WUD-Ducky#9]
Hello, finally I can run WUD-Ducky with ESP32 package 2.0.3-RC1. But I have big problem using mouse or keyboard when running payload. The server stuck at HID Timed out like forever. How can I fix this?

**Comment by tobozo** [comment]
hello  and thanks for your feedback

can you post a capture of your info page?

**Comment by maytinh365** [comment]
Here is the info page when I use mouse when running the paint draw payload
![Screenshot (42)](https://user-images.githubusercontent.com/105119993/167659003-c63828a7-fe54-4b84-8ff4-bdeee894870f.png)

**Comment by tobozo** [comment]
that's the log page, the info page comes up when you click on the upper left icon :information_source:

**Comment by tobozo** [comment]
closing this as inactive, feel free to reopen if something new comes up
